; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Tab3, x0 y0 w749 h481, Windows Tweaks | Utility | App downloader | Android Debugging | About
Gui Tab, 5
Gui Font, s20
Gui Add, Text, x208 y24 w408 h57 +0x200, Welcome to Toolkit 3.0
Gui Font
Gui Font, s20
Gui Add, Text, x24 y80 w408 h57 +0x200, Changelog:
Gui Font
Gui Font, s15
Gui Add, Text, x24 y128 w408 h57 +0x200, New code
Gui Font
Gui Font, s15
Gui Add, Text, x24 y176 w408 h34 +0x200, New Tweaks
Gui Font
Gui Font, s15
Gui Add, Text, x24 y208 w408 h57 +0x200, Android debugging 2.0
Gui Font
Gui Add, Button, x600 y432 w121 h29, Check for updates
Gui Tab, 4
Gui Add, Button, x8 y416 w730 h49 gsend, Send
Gui Add, Button, x392 y32 w168 h43 gmagisk, Install Magisk
Gui Add, Button, x392 y80 w168 h43 gbgapps, Install BitGapps
Gui Add, Button, x392 y128 w168 h43 glo, Launch Odin
Gui Add, Button, x392 y176 w168 h43 gtc, Install Total Commander
Gui Add, Button, x392 y224 w168 h43 grc, Install Root Checker
Gui Add, Button, x392 y272 w168 h43 gas, Install Aurora Store
Gui Add, Button, x392 y320 w168 h43 gad, Install Anydesk
Gui Add, Button, x568 y32 w168 h43 gre, Install Root Explorer
Gui Add, Button, x568 y80 w168 h43 gbr, Boot in Recovery
Gui Add, Button, x568 y128 w168 h43 gmgm, Install Magisk Manager
Gui Add, Button, x568 y272 w168 h43 gdm, Boot Download Mode 
Gui Add, Button, x568 y320 w168 h43 gmnc, Make a new command
Gui Add, Button, x568 y176 w168 h43 gfp, Install Flappy Bird
Gui Add, Button, x568 y224 w168 h43 gmpel, Install Minecraft Pocket Edition (Legacy)
Gui Add, Edit, x8 y32 w382 h380 vMyEditBox, Toolkit Android debugging 2.0
Gui Tab, 3
Gui Add, Button, x16 y32 w125 h43 gfirefox, Install Firefox
Gui Add, Button, x16 y80 w125 h43 gchrome, Install Chrome
Gui Add, Button, x16 y128 w125 h43 gadpc, Install Anydesk
Gui Add, Button, x16 y176 w125 h43 gsharex, Install ShareX
Gui Add, Button, x152 y32 w125 h43 gspotify, Install Spotify
Gui Add, Button, x152 y80 w125 h43 gmss, Install Microsoft Store
Gui Add, Button, x152 y128 w125 h43 gtg, Install Telegram
Gui Add, Button, x152 y176 w125 h43 gdiscord, Install Discord
Gui Tab, 2
Gui Add, Button, x16 y32 w125 h43 gdd, Double Driver
Gui Add, Button, x16 y80 w125 h43 grufus, Rufus 3.21
Gui Add, Button, x16 y128 w125 h43 gcpuz, CPU-Z
Gui Tab, 1
Gui Add, Button, x16 y32 w125 h43 grb, Restore Background
Gui Add, Button, x16 y80 w125 h43 grb11, Restore Dark Background (Win11)
Gui Add, Button, x16 y128 w125 h43 gdw, Disable Wifi
Gui Add, Button, x16 y176 w125 h43 grw, Re-enable Wifi
Gui Add, Button, x152 y32 w125 h43 guw, Upgrade Windows
Gui Add, Button, x152 y80 w125 h43 gaw, Activate Windows
Gui Add, Button, x152 y128 w125 h43 grwe, Restart Explorer
Gui Add, Button, x152 y176 w125 h43 gspc, Shutdown PC
Gui Tab

Gui Show, w747 h481, Toolkit 3.0
Return

GuiEscape:
GuiClose:
    ExitApp

ad:
run, %A_ScriptDir%\android_debugging\platform-tools\ad.bat

return 

mgm:
run, %A_ScriptDir%\android_debugging\platform-tools\mgm.bat

return

br:
run, %A_ScriptDir%\android_debugging\platform-tools\recovery.bat

return

re:
run, %A_ScriptDir%\android_debugging\platform-tools\re.bat

return 

rc:
run, %A_ScriptDir%\android_debugging\platform-tools\rc.bat

return 

tc:
run, %A_ScriptDir%\android_debugging\platform-tools\tc.bat

return

as:
run, %A_ScriptDir%\android_debugging\platform-tools\as.bat

return

fp:
run, %A_ScriptDir%\android_debugging\platform-tools\fp.bat

return

mpel:
run, %A_ScriptDir%\android_debugging\platform-tools\mpel.bat

return

lo:
run, %A_ScriptDir%\android_debugging\odin\odin.exe

magisk:
run, %A_ScriptDir%\android_debugging\platform-tools\magisk.bat

return

dm:
run, %A_ScriptDir%\android_debugging\platform-tools\dm.bat

return

mnc:
FileRecycle, %A_ScriptDir%\Cache\* 

bgapps:
run, %A_ScriptDir%\android_debugging\1.ahk

return

send:
    Gui, Submit, NoHide
    FileAppend, %MyEditBox%, %A_ScriptDir%\android_debugging\platform-tools\command.bat
    Run, %A_ScriptDir%\android_debugging\platform-tools\command.bat
    Return

firefox:
run, %A_ScriptDir%\app_installer\firefox.ahk

return

chrome:
run, %A_ScriptDir%\ch\ChromeSetup.exe

return

adpc:
run, %A_ScriptDir%\ch\Anydesk.exe

return

sharex:
run, %A_ScriptDir%\app_installer\sharex.ahk

return 

spotify:
run, %A_ScriptDir%\app_installer\spotify.ahk

return

mss:
run, %A_ScriptDir%\app_installer\ms-store\add-store.cmd

return

tg:
run, %A_ScriptDir%\app_installer\telegram.ahk

return

discord:
run, %A_ScriptDir%\app_installer\discord.ahk

return

cpuz:
run, %A_ScriptDir%\utility\cpuz\cpuz_x64.exe

return

rufus:
run, %A_ScriptDir%\utility\rufus\rufus-3.21p.exe

return

dd:
run, %A_ScriptDir%\utility\dd\dd.exe

return

rb:
run, %A_ScriptDir%\tweaks\rb.ahk

return 

rb11:
run, %A_ScriptDir%\tweaks\rb11.ahk

dw:
run ipconfig /release

return

rw:
run ipconfig /renew

return

uw:
run, %A_ScriptDir%\wu\win.ahk

return

aw:
run, %A_ScriptDir%\activator\mas.cmd

return 

rwe:
run, %A_ScriptDir%\tweaks\explorer.ahk

spc:
run, %A_ScriptDir%\tweaks\spc.bat